<?php
/**
 * Backup & Restore API
 * - backup: Generates a MySQL dump and returns as download
 * - restore: Accepts a SQL file upload and executes it
 * - listBackups: Lists available backup files
 */
require_once dirname(__DIR__) . '/config.php';
header('Content-Type: application/json');

if (!isLoggedIn() || !isAdmin()) {
    echo json_encode(['success' => false, 'error' => 'Unauthorized']);
    exit;
}

requireCSRF();

$conn = dbConnect();
$action = $_GET['action'] ?? $_POST['action'] ?? '';

switch ($action) {
    case 'backup':
        handleBackup($conn);
        break;
    case 'restore':
        handleRestore($conn);
        break;
    case 'listBackups':
        handleListBackups();
        break;
    default:
        echo json_encode(['success' => false, 'error' => 'Invalid action']);
}

function handleBackup($conn) {
    $dbName = $conn->real_escape_string(DB_NAME);
    $timestamp = date('Y-m-d_H-i-s');
    $filename = "backup_{$dbName}_{$timestamp}.sql";
    
    // Ensure backup directory exists
    $backupDir = dirname(__DIR__) . '/data/backups';
    if (!is_dir($backupDir)) {
        mkdir($backupDir, 0755, true);
    }
    
    $filepath = $backupDir . '/' . $filename;
    
    // Use mysqldump for proper SQL backup
    $mysqldump = 'C:\xampp\mysql\bin\mysqldump.exe';
    
    if (file_exists($mysqldump)) {
        $cmd = escapeshellcmd("{$mysqldump} -u " . escapeshellarg(DB_USER) . " --password=" . escapeshellarg(DB_PASS) . " " . escapeshellarg(DB_NAME) . " -r " . escapeshellarg($filepath));
        
        // Suppress password warning
        $output = [];
        $returnCode = 0;
        exec($cmd . " 2>NUL", $output, $returnCode);
        
        if ($returnCode === 0 && file_exists($filepath) && filesize($filepath) > 0) {
            // Download the file
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            header('Content-Length: ' . filesize($filepath));
            readfile($filepath);
            
            logActivity('backup_database', "Backup database berhasil: {$filename}");
            exit;
        }
    }
    
    // Fallback: PHP-based backup (slower but works without mysqldump)
    $tables = [];
    $result = $conn->query("SHOW TABLES");
    if ($result) {
        while ($row = $result->fetch_row()) {
            $tables[] = $row[0];
        }
    }
    
    $sqlDump = "-- Backup Database: {$dbName}\n";
    $sqlDump .= "-- Date: {$timestamp}\n";
    $sqlDump .= "-- Generated by: SIK SDN001GS\n\n";
    $sqlDump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
    
    foreach ($tables as $table) {
        $sqlDump .= "-- Table: {$table}\n";
        $sqlDump .= "DROP TABLE IF EXISTS `{$table}`;\n";
        
        // Get CREATE TABLE
        $createResult = $conn->query("SHOW CREATE TABLE `{$table}`");
        if ($createResult && $createRow = $createResult->fetch_row()) {
            $sqlDump .= $createRow[1] . ";\n\n";
        }
        
        // Get data
        $dataResult = $conn->query("SELECT * FROM `{$table}`");
        if ($dataResult && $dataResult->num_rows > 0) {
            while ($row = $dataResult->fetch_assoc()) {
                $values = array_map(function($v) use ($conn) {
                    if ($v === null) return 'NULL';
                    return "'" . $conn->real_escape_string($v) . "'";
                }, array_values($row));
                
                $sqlDump .= "INSERT INTO `{$table}` VALUES (" . implode(', ', $values) . ");\n";
            }
            $sqlDump .= "\n";
        }
    }
    
    $sqlDump .= "SET FOREIGN_KEY_CHECKS=1;\n";
    
    file_put_contents($filepath, $sqlDump);
    
    if (file_exists($filepath) && filesize($filepath) > 0) {
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . filesize($filepath));
        readfile($filepath);
        
        logActivity('backup_database', "Backup database berhasil (PHP fallback): {$filename}");
        exit;
    }
    
    echo json_encode(['success' => false, 'error' => 'Gagal membuat backup']);
}

function handleRestore($conn) {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        echo json_encode(['success' => false, 'error' => 'Method not allowed']);
        return;
    }
    
    if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
        echo json_encode(['success' => false, 'error' => 'File tidak ditemukan atau error']);
        return;
    }
    
    $file = $_FILES['sql_file'];
    
    // Validate file extension
    $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    if (!in_array($ext, ['sql', 'gz', 'zip'])) {
        echo json_encode(['success' => false, 'error' => 'Format file tidak didukung. Gunakan file .sql']);
        return;
    }
    
    // Validate file size (max 50MB)
    if ($file['size'] > 50 * 1024 * 1024) {
        echo json_encode(['success' => false, 'error' => 'Ukuran file terlalu besar (maks 50MB)']);
        return;
    }
    
    $sqlContent = file_get_contents($file['tmp_name']);
    if (empty($sqlContent)) {
        echo json_encode(['success' => false, 'error' => 'File kosong']);
        return;
    }
    
    // Split by semicolons and execute each statement
    $statements = array_filter(array_map('trim', explode(';', $sqlContent)));
    $successCount = 0;
    $errorCount = 0;
    $errors = [];
    
    foreach ($statements as $stmt) {
        $stmt = trim($stmt);
        if (empty($stmt) || strpos($stmt, '--') === 0 || strpos($stmt, '/*') === 0) continue;
        
        // Skip SET statements that might cause issues
        if (stripos($stmt, 'SET FOREIGN_KEY_CHECKS') === 0) {
            $conn->query($stmt);
            continue;
        }
        
        $result = $conn->query($stmt);
        if ($result) {
            $successCount++;
        } else {
            $errorCount++;
            if (count($errors) < 10) {
                $errors[] = $conn->error;
            }
        }
    }
    
    logActivity('restore_database', "Restore database: {$successCount} berhasil, {$errorCount} gagal dari file {$file['name']}");
    
    echo json_encode([
        'success' => true,
        'message' => "Restore selesai: {$successCount} perintah berhasil, {$errorCount} gagal",
        'success_count' => $successCount,
        'error_count' => $errorCount,
        'errors' => $errors
    ]);
}

function handleListBackups() {
    $backupDir = dirname(__DIR__) . '/data/backups';
    $backups = [];
    
    if (is_dir($backupDir)) {
        $files = glob($backupDir . '/backup_*.sql');
        foreach ($files as $file) {
            $backups[] = [
                'filename' => basename($file),
                'size' => filesize($file),
                'date' => date('Y-m-d H:i:s', filemtime($file))
            ];
        }
    }
    
    // Sort by date descending
    usort($backups, function($a, $b) {
        return strtotime($b['date']) - strtotime($a['date']);
    });
    
    echo json_encode(['success' => true, 'backups' => $backups]);
}
